version: "3.9"

services:
  fastapi:
    build: .
    container_name: design-pathway-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - design-pathway-net
    command: uvicorn fastapi_app:app --host 0.0.0.0 --port 8000 --reload

networks:
  design-pathway-net:
    external: true